### PR TITLE
Convert plugins to CommonJS and add tests

### PR DESCRIPTION
**Pull request by Gobie**
I converted plugins to CommonJS and added tests for each one of them.
Plugins can be loaded via require('combokeys/plugins/global-bind'), but there is still an issue with exposing plugins via amd.

### CODE REVIEW

**Comment by mightyiam** [comment]
Thank you very much, @Gobie. Superficial review. LGTM.

Tests pass in IE9–11, as well.

What do you mean about AMD? In order to use AMD, you'd have to convert the plugin files from CommonJS to some format that can be used as AMD.

There is an `npm-script` to do that with the main file.

**Comment by mightyiam** [comment]
Will you please fix the errors shown by `$ grunt eslint`?

**Comment by Gobie** [comment]
Using current AMD build with `npm run-script build` doesn't include plugins, maybe there should be separate one for combokeys with plugins, just a thought.

Lint issues fixed.

**Comment by mightyiam** [comment]
There seem to be two remaining lint issues. I'll merge and then fix.

Thank you very much.

**Comment by mightyiam** [comment]
@Gobie published `v2.3.0` for you.

**Comment by Gobie** [comment]
@mightyiam thx :+1:

**Pull request merged**
